name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "c8ff93424d63421e9caeb6221a15a8bb", preview_id = "c8ff93424d63421e9caeb6221a15a8bb" }
]
